# Generated by Django 4.2 on 2025-05-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0004_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='albums',
            field=models.ManyToManyField(blank=True, to='galerie.album'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
